config/routes.rb
Rails.application.routes.draw do
  resources :checkins
  resources :parking_spots

  root to: "visitors#index"
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
    def latitude
        (self.location ||= Point.new).y
      end

      def latitude=(value)
        (self.location ||= Point.new).y = value
      end

      def longitude
        (self.location ||= Point.new).x
      end

      def longitude=(value)
        (self.location ||= Point.new).x = value
      end
    end
end

app/models/parking_spot.rb
class ParkingSpot < ActiveRecord::Base

    def map

    end

end

app/controllers/application_controller.rb
require 'csv'
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:title, :location)
    end
end

app/controllers/parking_spots_controller.rb
class ParkingSpotsController < ApplicationController
  before_action :set_parking_spot, only: [:show, :edit, :update, :destroy]

  # GET /parking_spots
  # GET /parking_spots.json
  def index
    @parking_spots = ParkingSpot.all
  end

  # GET /parking_spots/1
  # GET /parking_spots/1.json
  def show
  end

  # GET /parking_spots/new
  def new
    @parking_spot = ParkingSpot.new
  end

  # GET /parking_spots/1/edit
  def edit
  end

  # POST /parking_spots
  # POST /parking_spots.json
  def create
    @parking_spot = ParkingSpot.new(parking_spot_params)

    respond_to do |format|
      if @parking_spot.save
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully created.' }
        format.json { render :show, status: :created, location: @parking_spot }
      else
        format.html { render :new }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_spots/1
  # PATCH/PUT /parking_spots/1.json
  def update
    respond_to do |format|
      if @parking_spot.update(parking_spot_params)
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking_spot }
      else
        format.html { render :edit }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_spots/1
  # DELETE /parking_spots/1.json
  def destroy
    @parking_spot.destroy
    respond_to do |format|
      format.html { redirect_to parking_spots_url, notice: 'Parking spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_spot
      @parking_spot = ParkingSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_spot_params
      params.require(:parking_spot).permit(:street, :city, :state, :zip, :lat, :lon, :side, :spots, :type)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/parking_spots_helper.rb
module ParkingSpotsHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.title %></td>
        <td><%= checkin.location %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @checkin.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @checkin.location %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 2.3 %>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'Home', root_path %><li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Parking', parking_spots_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Scoot Map" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Scoot Map" %>">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
      <!-- <header>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render 'layouts/navigation' %>
      </header> -->
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
</p>

app/views/parking_spots/_form.html.erb
<%= form_for(@parking_spot) do |f| %>
  <% if @parking_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_spot.errors.count, "error") %> prohibited this parking_spot from being saved:</h2>

      <ul>
      <% @parking_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :side %><br>
    <%= f.text_field :side %>
  </div>
  <div class="field">
    <%= f.label :spots %><br>
    <%= f.number_field :spots %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_spots/edit.html.erb
<h1>Editing parking_spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_spot %> |
<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/index.html.erb
<h1>Philadelphia Scooters Parking Map</h1>

<div id="map">
</div>

</div>

<table>
  <thead>
    <tr>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Side</th>
      <th>Spots</th>
      <th>Vehicle</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_spots.each do |parking_spot| %>
      <tr>
        <td class="street"><%= parking_spot.street %></td>
        <td><%= parking_spot.city %></td>
        <td><%= parking_spot.state %></td>
        <td><%= parking_spot.zip %></td>
        <td class="lat"><%= parking_spot.lat %></td>
        <td class="lon"><%= parking_spot.lon %></td>
        <td class="side"><%= parking_spot.side %></td>
        <td class="spots"><%= parking_spot.spots %></td>
        <td><%= parking_spot.vehicle %></td>
        <td> <a class= "marker_link" href="#">Marker</a></td>
        <td><%= link_to 'Show', parking_spot %></td>
        <td><%= link_to 'Edit', edit_parking_spot_path(parking_spot) %></td>
        <td><%= link_to 'Destroy', parking_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id ="map"> &nbsp</div>

<%= link_to 'New Parking spot', new_parking_spot_path %>

app/views/parking_spots/new.html.erb
<h1>New parking_spot</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Street:</strong>
  <%= @parking_spot.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @parking_spot.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @parking_spot.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @parking_spot.zip %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @parking_spot.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @parking_spot.lon %>
</p>

<p>
  <strong>Side:</strong>
  <%= @parking_spot.side %>
</p>

<p>
  <strong>Spots:</strong>
  <%= @parking_spot.spots %>
</p>

<p>
  <strong>Type:</strong>
  <%= @parking_spot.type %>
</p>

<%= link_to 'Edit', edit_parking_spot_path(@parking_spot) %> |
<%= link_to 'Back', parking_spots_path %>

app/views/visitors/index.html.erb
<h3>Welcome</h3>